# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07eed243c9963b38eb33b40b06195e84cff951a02069934119eeb4b978e7709adb7c6b4e110f0d229e73e6cbc11131cbbf25a3ee7ec5d41d19f825cff5178517
  foreign_database_username: <%= ENV["FOREIGN_DATABASE_USERNAME"] %>
  foreign_database_password: <%= ENV["FOREIGN_DATABASE_PASSWORD"] %>
  mapquest_api_key: <%= ENV["MAPQUEST_API_KEY"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>

test:
  secret_key_base: 8c525c6fd05f06cf30a93f9b729d4df8471e6c608eabe6db01aa85156ce726fd8f5f056136976e1f4a96fa8b691617657f1962637cd0d3d4fe22005253e3d4d2
  foreign_database_username: <%= ENV["FOREIGN_DATABASE_USERNAME"] %>
  foreign_database_password: <%= ENV["FOREIGN_DATABASE_PASSWORD"] %>
  mapquest_api_key: <%= ENV["MAPQUEST_API_KEY"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  foreign_database_username: <%= ENV["FOREIGN_DATABASE_USERNAME"] %>
  foreign_database_password: <%= ENV["FOREIGN_DATABASE_PASSWORD"] %>
  mapquest_api_key: <%= ENV["MAPQUEST_API_KEY"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  foreign_database_username: <%= ENV["FOREIGN_DATABASE_USERNAME"] %>
  foreign_database_password: <%= ENV["FOREIGN_DATABASE_PASSWORD"] %>
  mapquest_api_key: <%= ENV["MAPQUEST_API_KEY"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
