FactoryBot.define do
  factory :development do
    creator_id 1
    rdv false
    asofright false
    ovr55 false
    clusteros false
    phased false
    stalled false
    name "Seaport"
    status "MyString"
    desc "MyText"
    project_url "MyString"
    mapc_notes "MyText"
    tagline "MyString"
    address "123 Main Street"
    state "MyString"
    zip_code "MyString"
    height 1
    stories 1
    year_compl 1
    prjarea 1
    singfamhu 1
    twnhsmmult 1
    lgmultifam 1
    tothu 1
    gqpop 1
    rptdemp 1
    emploss 1
    estemp 1
    commsf 1
    hotelrms 1
    onsitepark 1
    total_cost 1
    team_membership_count 1
    cancelled false
    private false
    fa_ret 1.5
    fa_ofcmd 1.5
    fa_indmf 1.5
    fa_whs 1.5
    fa_rnd 1.5
    fa_edinst 1.5
    fa_other 1.5
    fa_hotel 1.5
    other_rate 1.5
    affordable 1.5
    latitude "9.99"
    longitude "9.99"
    parcel_id "MyString"
    mixed_use false
    point ""
    programs "MyString"
    forty_b false
    residential false
    commercial false
    municipality "Boston"
  end
end
