import DS from 'ember-data'; 
const { Model, attr, belongsTo } = DS;


export default Model.extend({

  user: belongsTo({ async: true }),

  name: attr('string'),
  status: attr('string'),
  desc: attr('string'),
  projectUrl: attr('string'),
  mapcNotes: attr('string'),
  tagline: attr('string'),
  address: attr('string'),
  state: attr('string'),
  zipCode: attr('string'),
  parcelId: attr('string'),
  programs: attr('string'),
  municipality: attr('string'),
  developerName: attr('string'),

  height: attr('number'),
  stories: attr('number'),
  yearCompl: attr('number'),
  prjarea: attr('number'),
  singfamhu: attr('number'),
  twnhsmmult: attr('number'),
  lgmultifam: attr('number'),
  tothu: attr('number'),
  gqpop: attr('number'),
  rptdemp: attr('number'),
  emploss: attr('number'),
  estemp: attr('number'),
  commsf: attr('number'),
  hotelrms: attr('number'),
  onsitepark: attr('number'),
  totalCost: attr('number'),
  teamMembershipCount: attr('number'),
  faRet: attr('number'),
  faOfcmd: attr('number'),
  faIndmf: attr('number'),
  faWhs: attr('number'),
  faRnd: attr('number'),
  faEdinst: attr('number'),
  faOther: attr('number'),
  faHotel: attr('number'),
  otherRate: attr('number'),
  affordable: attr('number'),
  latitude: attr('number'),
  longitude: attr('number'),

  rdv: attr('boolean'),
  asofright: attr('boolean'),
  over55: attr('boolean'),
  clusteros: attr('boolean'),
  phased: attr('boolean'),
  stalled: attr('boolean'),
  cancelled: attr('boolean', { default: false }),
  private: attr('boolean', { default: false }),
  fortyB: attr('boolean'),
  mixedUse: attr('boolean'),

  residential: attr('boolean'),
  commercial: attr('boolean'),

  createdAt: attr('date'),
  updatedAt: attr('date'),

});
